# -*- coding: utf-8 -*-
"""Covid-19 Tasks.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SYoX_BLVEs5lIk6SP8J3XUNCwNCvKerC
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
import plotly.express as px

df = pd.read_csv('/content/drive/MyDrive/WHO-COVID-19-global-daily-data.csv')
df.head()

df['Date_reported'] = pd.to_datetime(df['Date_reported'])

def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:
        return 'Autumn'

df['season'] = df['Date_reported'].dt.month.apply(get_season)

print(df[['season']].value_counts())

df.season.describe()

season_summary = df.groupby('season')[['New_deaths', 'New_cases']].sum()
print(season_summary)

season_summary = df.groupby('season')[['New_deaths', 'New_cases']].sum()

season_summary.plot(
    kind='bar',
    figsize=(10, 8),
    color=['red', 'blue']
)

plt.title("Total Deaths & Cases per Season")
plt.ylabel("Count")
plt.xlabel("Season")
plt.xticks(rotation=0)
plt.legend(["New Deaths", "New Cases"])
plt.show()

season_summary.plot(
    kind='bar',
    figsize=(8, 5),
    color=['red', 'blue']
)

plt.yscale("log")
plt.title("Total Deaths & Cases per Season (Log Scale)")
plt.ylabel("Count (Log Scale)")
plt.xlabel("Season")
plt.xticks(rotation=0)
plt.legend(["New Deaths", "New Cases"])
plt.show()

region_season_summary = df.groupby(['WHO_region', 'season'])[['New_deaths', 'New_cases']].sum()
print(region_season_summary.head(20))

region_season_summary.unstack().plot(kind='bar', figsize=(14,7))
plt.title("Total Deaths & Cases by Region and Season")
plt.ylabel("Count")
plt.show()