# -*- coding: utf-8 -*-
"""Titanic_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RVa4S4kbHBLTtx19-hLLUqQPXMAOBl6d
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
drive.mount('/content/drive')
df=pd.read_csv('/content/drive/MyDrive/train.csv')
df.head()

"""**(1)Try to impute Missing Values in "Embarked" feature instead of Dropping**"""

df['Embarked'].describe()

df['Embarked'].value_counts()

df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

df['Embarked'].describe()

df['Embarked'].value_counts()

"""**(2)Create New Feature: "family_size" to combine "parch" and " sibsp" and explore it with Survival Rate**"""

df['family_size']=df['SibSp']+df['Parch']+1

"""**(3)How many passengers were alone? What is their Survival Rate ?**"""

alone = df[df['family_size'] == 1]
num_alone = alone.shape[0]
print(f"Number of passengers alone :{num_alone}")

survival_rate_alone = alone['Survived'].mean()
print("Survival rate of passengers who were alone:", survival_rate_alone)

"""**
(4)What are top 3 categories from "family_size" have highest survival Rate ?**
"""

df.groupby('family_size')['Survived'].mean().nlargest(3)

"""**(5)Try differnet age groups

Which age groups have the lowest and highest survival rate for both females and males?**
"""

df['Age_Group'] = pd.cut(df['Age'],
                         bins=[0, 12, 18, 35, 50, 80],
                         labels=['Child', 'Teen', 'Young Adult', 'Adult', 'Senior'])

Survival_Rates = df.groupby(['Sex', 'Age_Group'], observed=False)['Survived'].mean().reset_index()

Lowest = Survival_Rates.loc[Survival_Rates.groupby('Sex')['Survived'].idxmin()]
print("Lowest Survival Rates:")
print(Lowest)

Highest = Survival_Rates.loc[Survival_Rates.groupby('Sex')['Survived'].idxmax()]
print("\nHighest Survival Rates:")
print(Highest)

sns.barplot(x='Age_Group', y='Survived', hue='Sex', data=Survival_Rates)
plt.title("Survival Rate By Age Group And Sex")
plt.show()